MODULES+=	ndk

MODULE_SUMMARY_ndk=	3rd-party NDK dynamic module

MODULE_CONTRIB_DEPS_ndk=	ngx_devel_kit

include $(foreach dep,$(MODULE_CONTRIB_DEPS_ndk),$(CONTRIB)/src/$(dep)/version)

MODULE_VERSION_ndk=	$(NGX_DEVEL_KIT_VERSION)
MODULE_RELEASE_ndk=	1

MODULE_VERSION_PREFIX_ndk=$(MODULE_TARGET_PREFIX)

MODULE_SOURCES_ndk=	ngx_devel_kit-$(NGX_DEVEL_KIT_VERSION).tar.gz

MODULE_CONFARGS_ndk=	--add-dynamic-module=$(MODSRC_PREFIX)ngx_devel_kit-$(NGX_DEVEL_KIT_VERSION)

MODULE_PATCHES_ndk=	$(CONTRIB)/src/ngx_devel_kit/0001-fix-complex-value-end-code-for-nginx-1.31.3.patch

MODULE_CC_OPT_ndk=-DNDK_SET_VAR -DNDK_UPSTREAM_LIST
MODULE_CC_OPT_DEBUG_ndk=$(MODULE_CC_OPT_ndk)

NDK_DEPENDENCY_TAG=nginx$(MODULE_SUFFIX)-module-ndk nginx$(MODULE_SUFFIX)-module-ndk-r$(TARGET_VERSION)

define MODULE_POST_ndk
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_ndk) for $(MODULE_SUMMARY_PREFIX) has been installed.
To enable this module, add the following to /etc/nginx/nginx.conf
and reload nginx:

    load_module modules/ndk_http_module.so;

Please refer to the module documentation for further details:
https://github.com/simpl/ngx_devel_kit

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_ndk
